[package]
name = "ingester"
version = "0.1.0"
authors = ["joxer <diego.luca.candido@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.19"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
